// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _01_RazorPages.Data;

#nullable disable

namespace _01_RazorPages.Migrations
{
    [DbContext(typeof(TablesContext))]
    partial class TablesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("_01_RazorPages.Data.Models.Table1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK__Table1s");

                    b.ToTable("table1s");
                });

            modelBuilder.Entity("_01_RazorPages.Data.Models.Table2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Table1Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("PK__Table2s");

                    b.HasIndex("Table1Id");

                    b.ToTable("table2s");
                });

            modelBuilder.Entity("_01_RazorPages.Data.Models.Table2", b =>
                {
                    b.HasOne("_01_RazorPages.Data.Models.Table1", "Table1")
                        .WithMany("Table2s")
                        .HasForeignKey("Table1Id")
                        .IsRequired()
                        .HasConstraintName("FK_Table2s_Table1s");

                    b.Navigation("Table1");
                });

            modelBuilder.Entity("_01_RazorPages.Data.Models.Table1", b =>
                {
                    b.Navigation("Table2s");
                });
#pragma warning restore 612, 618
        }
    }
}
